DiscordBot:
  Credentials:
    Email: 
    Password: 
  TextChannels:
    Bot: ''
    InGame: ''
  Messages:
    CommandPrefix: '!'
    ConsoleOutput: true
    InGameFormat: '&c[Discord] &f%author%:'
    InGameChat: true
    SyncChat: false
  Listeners:
    MainBot: true
    SendInGame: false
    SendDiscord: true
    UserAvatarUpdate: true
    UserGameUpdate: true
    UserNameUpdate: true
    UserOnlineStatusUpdate: true
    VoiceServerDeaf: true
    VoiceServerMute: true