name: ${project.artifactId}
main: io.github.lxgaming.discordbot.DiscordBot
version: ${project.version}
author: LX_Gaming
website: http://www.lxgaming.github.io
commands:
  discordbot:
    description: Display plugin information.
    usage: /<command>
  discordchat:
    description: Send messages to Discord.
    usage: /<command> <message>
  dcc:
    description: Send messages to Discord.
    usage: /<command> <message>
permissions:
  DiscordBot.Chat:
    description: Allow players to message Discord.