name: ${project.artifactId}
main: io.github.lxgaming.discordbot.DiscordBot
version: ${project.version}
description: Cross communications with Discord and your Minecraft server.
author: LX_Gaming
website: http://www.lxgaming.github.io
commands:
  discordbot:
    description: Display plugin information.
    usage: /<command>
  discordchat:
    description: Send messages to Discord.
    usage: /<command> <message>
    aliases: [dcc]
permissions:
  DiscordBot.CommandChat:
    description: Send messages to Discord via command.
  DiscordBot.GlobalChat:
    description: Send messages to Discord via global chat.
  DiscordBot.ReceiveDiscordChat:
    description: Receive Discord messages ingame.
  DiscordBot.Silent:
    description: Players with this permission won't trigger events.