DiscordBot:
  Credentials:
    BotToken: ''
  TextChannels:
    Bot: ''
    InGame: ''
  Messages:
    Locale: 'en'
    CommandPrefix: '!'
    ConsoleOutput: true
    SendInGame: true
    SendDiscord: true
  Listeners:
    MainBot: true
    UserAvatarUpdate: true
    UserGameUpdate: true
    UserNameUpdate: true
    UserOnlineStatusUpdate: true
    VoiceServerDeaf: true
    VoiceServerMute: true
  Events:
    PlayerChat: true
    PlayerJoin: true
    PlayerQuit: true
    PlayerDeath: true