name: ${project.artifactId}
main: io.github.lxgaming.discordbot.DiscordBot
version: ${project.version}
author: LX_Gaming
website: http://www.lxgaming.github.io
commands:
  discordbot:
    description: Display plugin information.
    usage: /<command>
  discordchat:
    description: Send message to Discord.
    usage: /<command>
  dcc:
    description: Send message to Discord.
    usage: /<command>
permissions:
  DiscordBot.CommandChat:
    description: Send messages to Discord via command.
  DiscordBot.GlobalChat:
    description: Send messages to Discord via global chat.
  DiscordBot.ReceiveDiscordChat:
    description: Receive Discord messages ingame.