name: ${project.artifactId}
main: io.github.lxgaming.discordbot.DiscordBot
version: ${project.version}
author: LX_Gaming
website: http://www.lxgaming.github.io
commands:
  discordbot:
    description: Display plugin information.
    usage: /<command>
permissions:
  DiscordBot.Chat:
    description: Allows Discord Chat.